// AUTO-GENERATED by oz-policy-codegen (Phase 3 Track-B). DO NOT EDIT.
// Source spec hash: a3f9ddc9f4bd3e5372bf65e0d7c17ff8640e3f26b4af65e5d1dfbd45723426be
// Template family : argumentpattern
//
// This contract is the WASM body of one Generated PolicySlot. It is built as a
// `cdylib`, deployed via the Phase 2 installer, and registered against a smart
// account ContextRule. Every constraint primitive carried by the source spec
// has its own enforce branch below; omitted branches were not emitted so the
// WASM payload stays minimal.
//
// Security invariants (verified by Phase 9 audit lints, see plan.md):
//   1. `smart_account.require_auth()` is the FIRST line of every state-mutating
//      entry point (`install`, `enforce`, `uninstall`).
//   2. Every storage key is namespaced by `(smart_account, context_rule_id)` so
//      two policies sharing a contract WASM cannot leak state across rules.
//   3. Every match arm has an explicit default-reject branch — no silent
//      passthroughs.
//   4. No `unsafe`, no `std::mem::transmute`. `#![forbid(unsafe_code)]`.
//   5. Linked against `stellar-accounts = =0.7.1` (see docs/codegen-dependency-mode.md).

#![no_std]
#![forbid(unsafe_code)]

// Some imports are only used when specific constraint primitives are emitted.
// We import the full surface unconditionally and silence the unused-import
// lint rather than render conditional `use` lines (the rendered source must
// remain readable to auditors).
#[allow(unused_imports)]
use soroban_sdk::{
    auth::{Context, ContractContext},
    contract, contracterror, contractevent, contractimpl, contracttype, panic_with_error,
    symbol_short, Address, Bytes, Env, String, Symbol, TryFromVal, Vec,
};

use stellar_accounts::policies::Policy as PolicyTrait;
use stellar_accounts::smart_account::{ContextRule, Signer};

// -------------------------------------------------------------------------
// Storage keys — every variant is keyed by (smart_account, context_rule_id)
// per the cross-rule replay mitigation in research §12.
// -------------------------------------------------------------------------

#[contracttype]
pub enum StorageKey {
    /// Marker that the policy is installed for (smart_account, rule_id).
    Installed(Address, u32),
}

// -------------------------------------------------------------------------
// Install parameters. The struct shape is fixed at codegen time; consumers
// constructed it via `IntoVal` in the installer (see Phase 2).
// -------------------------------------------------------------------------

#[contracttype]
#[derive(Clone)]
pub struct InstallParams {
    /// Placeholder marker so the struct is never empty (Soroban contracttype
    /// rejects unit structs). Currently always `0`. Future enhancement: per-
    /// rule installer-time overrides.
    pub _marker: u32,
}

// -------------------------------------------------------------------------
// Errors. Codes use the 1xxx range so they never collide with OZ's 3xxx
// SmartAccount / policy errors (see docs/oz-internal-shapes.md §5).
// -------------------------------------------------------------------------

#[contracterror]
#[derive(Copy, Clone, Debug, PartialEq)]
#[repr(u32)]
pub enum PolicyError {
    /// Default-reject: a code path that should be unreachable in a well-formed
    /// invocation was hit. Always indicates the caller exceeded the spec's
    /// declarative permissions.
    Default = 1000,
    /// Policy not installed for the given (smart_account, context_rule_id).
    NotInstalled = 1001,
    /// Already installed for the given (smart_account, context_rule_id).
    AlreadyInstalled = 1002,
    /// One of the typed-argument constraints did not match.
    ArgumentMismatch = 1020,
}

// -------------------------------------------------------------------------
// Events. Emitted for off-chain indexers + the Phase 4 simulation harness.
// -------------------------------------------------------------------------

#[contractevent]
#[derive(Clone)]
pub struct PolicyInstalled {
    #[topic]
    pub smart_account: Address,
    pub context_rule_id: u32,
}

#[contractevent]
#[derive(Clone)]
pub struct PolicyEnforced {
    #[topic]
    pub smart_account: Address,
    pub context_rule_id: u32,
}

#[contractevent]
#[derive(Clone)]
pub struct PolicyUninstalled {
    #[topic]
    pub smart_account: Address,
    pub context_rule_id: u32,
}

// -------------------------------------------------------------------------
// Contract — implements stellar_accounts::Policy.
// -------------------------------------------------------------------------

#[contract]
pub struct Policy;

#[contractimpl]
impl PolicyTrait for Policy {
    type AccountParams = InstallParams;

    fn install(
        e: &Env,
        _install_params: Self::AccountParams,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        // SECURITY: smart_account auth is mandatory on every mutating entry.
        smart_account.require_auth();

        let key = StorageKey::Installed(smart_account.clone(), context_rule.id);
        if e.storage().persistent().has(&key) {
            panic_with_error!(e, PolicyError::AlreadyInstalled);
        }
        e.storage().persistent().set(&key, &true);

        PolicyInstalled {
            smart_account: smart_account.clone(),
            context_rule_id: context_rule.id,
        }
        .publish(e);
    }

    fn enforce(
        e: &Env,
        context: Context,
        _authenticated_signers: Vec<Signer>,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        // SECURITY: smart_account auth is the FIRST line — research §12.
        smart_account.require_auth();

        let key = StorageKey::Installed(smart_account.clone(), context_rule.id);
        if !e.storage().persistent().has(&key) {
            panic_with_error!(e, PolicyError::NotInstalled);
        }

        // -----------------------------------------------------------------
        // Extract the call shape. `Context::Contract` covers the
        // CallContract rule type (direct invocation). For Default rules the
        // execute() wrapper convention applies and the caller routes the
        // inner call through `args[0..2]` — but per the canonical Policy
        // trait shape this contract is always invoked with a `Context::Contract`
        // already decoded by the smart account, so we match that variant.
        // Anything else is default-rejected.
        // -----------------------------------------------------------------
        let _ = &context_rule;
        match &context {
            Context::Contract(ContractContext { contract, fn_name, args }) => {
                // --- argument_pattern ---
// Typed slot match against a specific (fn_name, arg_index). Each entry encodes
// the matcher into a Rust expression operating on the decoded `args.get(idx)`
// Val. Unrecognised arms default-reject via ArgumentMismatch.
{
    if fn_name == &symbol_short!("transfer") {
        let arg_val = args.get(0u32)
            .unwrap_or_else(|| panic_with_error!(e, PolicyError::ArgumentMismatch));
        let decoded = u32::try_from_val(e, &arg_val)
            .unwrap_or_else(|_| panic_with_error!(e, PolicyError::ArgumentMismatch));
        if decoded != 42u32 {
            panic_with_error!(e, PolicyError::ArgumentMismatch);
        }
    }
}
                // Suppress unused-variable warnings when only a subset of
                // primitives is emitted.
                let _ = (contract, fn_name, args);
            }
            _ => {
                // Default-reject: CreateContract / CreateContractHostFn paths
                // are not expressible by this template family.
                panic_with_error!(e, PolicyError::Default);
            }
        }

        PolicyEnforced {
            smart_account: smart_account.clone(),
            context_rule_id: context_rule.id,
        }
        .publish(e);
    }

    fn uninstall(e: &Env, context_rule: ContextRule, smart_account: Address) {
        // SECURITY: smart_account auth is mandatory on every mutating entry.
        smart_account.require_auth();

        let key = StorageKey::Installed(smart_account.clone(), context_rule.id);
        if !e.storage().persistent().has(&key) {
            panic_with_error!(e, PolicyError::NotInstalled);
        }
        e.storage().persistent().remove(&key);

        PolicyUninstalled {
            smart_account: smart_account.clone(),
            context_rule_id: context_rule.id,
        }
        .publish(e);
    }
}