// AUTO-GENERATED by oz-policy-codegen (Phase 3 Track-B). DO NOT EDIT.
// Source spec hash: 9ab994b4e4cb82ddd67164206247e0f36fd1371e92bb543af25d058c18ee2b75
// Template family : functionallowlist
//
// This contract is the WASM body of one Generated PolicySlot. It is built as a
// `cdylib`, deployed via the Phase 2 installer, and registered against a smart
// account ContextRule. Every constraint primitive carried by the source spec
// has its own enforce branch below; omitted branches were not emitted so the
// WASM payload stays minimal.
//
// Security invariants (verified by Phase 9 audit lints, see plan.md):
//   1. `smart_account.require_auth()` is the FIRST line of every state-mutating
//      entry point (`install`, `enforce`, `uninstall`).
//   2. Every storage key is namespaced by `(smart_account, context_rule_id)` so
//      two policies sharing a contract WASM cannot leak state across rules.
//   3. Every match arm has an explicit default-reject branch — no silent
//      passthroughs.
//   4. No `unsafe`, no `std::mem::transmute`. `#![forbid(unsafe_code)]`.
//   5. Linked against `stellar-accounts = =0.7.1` (see docs/codegen-dependency-mode.md).

#![no_std]
#![forbid(unsafe_code)]

// Some imports are only used when specific constraint primitives are emitted.
// We import the full surface unconditionally and silence the unused-import
// lint rather than render conditional `use` lines (the rendered source must
// remain readable to auditors).
#[allow(unused_imports)]
use soroban_sdk::{
    auth::{Context, ContractContext},
    contract, contracterror, contractevent, contractimpl, contracttype, panic_with_error,
    symbol_short, Address, Bytes, Env, String, Symbol, TryFromVal, Vec,
};

use stellar_accounts::policies::Policy as PolicyTrait;
use stellar_accounts::smart_account::{ContextRule, Signer};

// -------------------------------------------------------------------------
// Storage keys — every variant is keyed by (smart_account, context_rule_id)
// per the cross-rule replay mitigation in research §12.
// -------------------------------------------------------------------------

#[contracttype]
pub enum StorageKey {
    /// Marker that the policy is installed for (smart_account, rule_id).
    Installed(Address, u32),
    /// `Vec<u32>` of recent enforce ledger sequences for rolling-window
    /// call-frequency accounting.
    FreqLedgers(Address, u32),
}

// -------------------------------------------------------------------------
// Install parameters. The struct shape is fixed at codegen time; consumers
// constructed it via `IntoVal` in the installer (see Phase 2).
// -------------------------------------------------------------------------

#[contracttype]
#[derive(Clone)]
pub struct InstallParams {
    /// Placeholder marker so the struct is never empty (Soroban contracttype
    /// rejects unit structs). Currently always `0`. Future enhancement: per-
    /// rule installer-time overrides.
    pub _marker: u32,
}

// -------------------------------------------------------------------------
// Errors. Codes use the 1xxx range so they never collide with OZ's 3xxx
// SmartAccount / policy errors (see docs/oz-internal-shapes.md §5).
// -------------------------------------------------------------------------

#[contracterror]
#[derive(Copy, Clone, Debug, PartialEq)]
#[repr(u32)]
pub enum PolicyError {
    /// Default-reject: a code path that should be unreachable in a well-formed
    /// invocation was hit. Always indicates the caller exceeded the spec's
    /// declarative permissions.
    Default = 1000,
    /// Policy not installed for the given (smart_account, context_rule_id).
    NotInstalled = 1001,
    /// Already installed for the given (smart_account, context_rule_id).
    AlreadyInstalled = 1002,
    /// Function name is not on the allowlist.
    FunctionNotAllowed = 1010,
    /// `i128` amount argument fell outside the allowed range.
    AmountOutOfRange = 1030,
    /// Call frequency exceeded `max_calls` within `window_ledgers`.
    CallFrequencyExceeded = 1060,
}

// -------------------------------------------------------------------------
// Events. Emitted for off-chain indexers + the Phase 4 simulation harness.
// -------------------------------------------------------------------------

#[contractevent]
#[derive(Clone)]
pub struct PolicyInstalled {
    #[topic]
    pub smart_account: Address,
    pub context_rule_id: u32,
}

#[contractevent]
#[derive(Clone)]
pub struct PolicyEnforced {
    #[topic]
    pub smart_account: Address,
    pub context_rule_id: u32,
}

#[contractevent]
#[derive(Clone)]
pub struct PolicyUninstalled {
    #[topic]
    pub smart_account: Address,
    pub context_rule_id: u32,
}

// -------------------------------------------------------------------------
// Contract — implements stellar_accounts::Policy.
// -------------------------------------------------------------------------

#[contract]
pub struct Policy;

#[contractimpl]
impl PolicyTrait for Policy {
    type AccountParams = InstallParams;

    fn install(
        e: &Env,
        _install_params: Self::AccountParams,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        // SECURITY: smart_account auth is mandatory on every mutating entry.
        smart_account.require_auth();

        let key = StorageKey::Installed(smart_account.clone(), context_rule.id);
        if e.storage().persistent().has(&key) {
            panic_with_error!(e, PolicyError::AlreadyInstalled);
        }
        e.storage().persistent().set(&key, &true);

        PolicyInstalled {
            smart_account: smart_account.clone(),
            context_rule_id: context_rule.id,
        }
        .publish(e);
    }

    fn enforce(
        e: &Env,
        context: Context,
        _authenticated_signers: Vec<Signer>,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        // SECURITY: smart_account auth is the FIRST line — research §12.
        smart_account.require_auth();

        let key = StorageKey::Installed(smart_account.clone(), context_rule.id);
        if !e.storage().persistent().has(&key) {
            panic_with_error!(e, PolicyError::NotInstalled);
        }

        // -----------------------------------------------------------------
        // Extract the call shape. `Context::Contract` covers the
        // CallContract rule type (direct invocation). For Default rules the
        // execute() wrapper convention applies and the caller routes the
        // inner call through `args[0..2]` — but per the canonical Policy
        // trait shape this contract is always invoked with a `Context::Contract`
        // already decoded by the smart account, so we match that variant.
        // Anything else is default-rejected.
        // -----------------------------------------------------------------
        let _ = &context_rule;
        match &context {
            Context::Contract(ContractContext { contract, fn_name, args }) => {
                // --- function_allowlist ---
// Only the listed function symbols may be invoked. Names ≤ 9 ASCII chars use
// `symbol_short!`; longer ones use `Symbol::new(env, "…")`. Unrecognised
// fn_name → FunctionNotAllowed.
{
    let mut matched = false;
    if fn_name == &symbol_short!("transfer") {
        matched = true;
    }
    if !matched {
        panic_with_error!(e, PolicyError::FunctionNotAllowed);
    }
}
                // --- amount_range ---
// Constrains an `i128` argument to `[min, max]` (inclusive). Either bound may
// be open (None); both-open is forbidden at synthesis time so always at least
// one branch is emitted.
{
    if fn_name == &symbol_short!("transfer") {
        let arg_val = args.get(2u32)
            .unwrap_or_else(|| panic_with_error!(e, PolicyError::AmountOutOfRange));
        let amount = i128::try_from_val(e, &arg_val)
            .unwrap_or_else(|_| panic_with_error!(e, PolicyError::AmountOutOfRange));
        if amount > 1000000000i128 {
            panic_with_error!(e, PolicyError::AmountOutOfRange);
        }
    }
}
                // --- call_frequency ---
// Rolling window: keep the ledger sequences of admitted enforce calls in
// `StorageKey::FreqLedgers`. On each new enforce, evict entries older than
// `current - window_ledgers`, then panic if remaining count >= max_calls,
// else push the current ledger and persist. TTL extended on every write.
{
    let current = e.ledger().sequence();
    let freq_key = StorageKey::FreqLedgers(smart_account.clone(), context_rule.id);
    let mut history: Vec<u32> = e
        .storage()
        .persistent()
        .get(&freq_key)
        .unwrap_or_else(|| Vec::new(e));

    // Evict entries strictly older than the rolling-window cutoff.
    let cutoff = current.saturating_sub(17280u32);
    let mut kept: Vec<u32> = Vec::new(e);
    for i in 0..history.len() {
        let seq = history.get(i).unwrap();
        if seq > cutoff {
            kept.push_back(seq);
        }
    }
    history = kept;

    if history.len() >= 3u32 {
        panic_with_error!(e, PolicyError::CallFrequencyExceeded);
    }

    history.push_back(current);
    e.storage().persistent().set(&freq_key, &history);
    // Default TTL extension: 30 days in ledgers (matches OZ primitives).
    e.storage()
        .persistent()
        .extend_ttl(&freq_key, 17_280u32 * 29u32, 17_280u32 * 30u32);
}
                // Suppress unused-variable warnings when only a subset of
                // primitives is emitted.
                let _ = (contract, fn_name, args);
            }
            _ => {
                // Default-reject: CreateContract / CreateContractHostFn paths
                // are not expressible by this template family.
                panic_with_error!(e, PolicyError::Default);
            }
        }

        PolicyEnforced {
            smart_account: smart_account.clone(),
            context_rule_id: context_rule.id,
        }
        .publish(e);
    }

    fn uninstall(e: &Env, context_rule: ContextRule, smart_account: Address) {
        // SECURITY: smart_account auth is mandatory on every mutating entry.
        smart_account.require_auth();

        let key = StorageKey::Installed(smart_account.clone(), context_rule.id);
        if !e.storage().persistent().has(&key) {
            panic_with_error!(e, PolicyError::NotInstalled);
        }
        e.storage().persistent().remove(&key);

        let freq_key = StorageKey::FreqLedgers(smart_account.clone(), context_rule.id);
        if e.storage().persistent().has(&freq_key) {
            e.storage().persistent().remove(&freq_key);
        }

        PolicyUninstalled {
            smart_account: smart_account.clone(),
            context_rule_id: context_rule.id,
        }
        .publish(e);
    }
}